### ISSUE TITLE
Transfer to clj-commons?

### ISSUE THREAD

**Issue by seancorfield** [clj-commons/clooj#131]
Hi Arthur,

Some folks are interested in resurrecting Clooj and maintaining it under the https://clj-commons.org umbrella.

Some initial work has been done to get Clooj back up and running on modern Clojure/JDKs at https://github.com/eerohele/clooj and we could transfer that repo to clj-commons, but it would be preferable to transfer your original repo to clj-commons so that GitHub would handle redirects etc for any forks that exist.

Would you consider that?

If so, we can add you to the clj-commons organization so that you could initiate a transfer into it.

**Comment by arthuredelstein** [comment]
Hi Sean,

Thanks for reaching out! I would be happy to do that and hand over
maintenance to anyone who would like to do it.

Best regards,
Arthur

**Comment by seancorfield** [comment]
Thanks! I've added you to the clj-commons org so you should be able to initiate a transfer of the repo. LMK if you need any additional help or information.

**Comment by arthuredelstein** [comment]
OK, the transfer seems to have worked!

I'm excited to see someone bringing it back to life! I'm sure it needs a lot of work. Also as I recall the UI code is kind of messy and could do with being migrated to a modern reactive programming style.

**Comment by seancorfield** [comment]
Thank you!
